version: '3'
services:
  postgres:
    container_name: postgres
    image: postgres:14
    volumes:
      - pgsql_data:/var/lib/postgresql/data
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_INITDB_ARGS: "--encoding=UTF-8"

  mysql:
    container_name: mysql
    image: mysql:8
    # volumes:
    #   - ./mysql:/var/lib/mysql
    ports:
      - 3306:3306
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=test
      - MYSQL_USER=test
      - MYSQL_PASSWORD=test

  phpmyadmin:
    container_name: phpMyAdmin
    depends_on:
      - mysql
    image: phpmyadmin/phpmyadmin
    environment:
      PMA_HOST: mysql
    restart: always
    ports:
      - "8000:80"

  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4
    volumes:
      - pgadmin_data:/var/lib/pgadmin
    ports:
        - 8888:80
    environment:
        PGADMIN_DEFAULT_EMAIL: admin@example.com
        PGADMIN_DEFAULT_PASSWORD: password
    depends_on:
      - postgres

  php:
    container_name: php-apache
    build: .
    volumes:
      - .:/var/www/html
      - .:/work
      - composer:/work/vendor
    ports:
      - 8080:80
    depends_on:
      - mysql

volumes:
  pgsql_data:
  pgadmin_data:
  composer:
