version: '3'
services:
  mysql:
    container_name: mysql
    image: mysql:8
    # volumes:
    #   - ./mysql:/var/lib/mysql
    ports:
      - 3306:3306
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=test
      - MYSQL_USER=test
      - MYSQL_PASSWORD=test

  phpmyadmin:
    container_name: phpMyAdmin
    depends_on:
      - mysql
    image: phpmyadmin/phpmyadmin
    environment:
      PMA_HOST: mysql
    restart: always
    ports:
      - "8000:80"

  php:
    container_name: php-apache
    build: .
    volumes:
      - .:/var/www/html
    ports:
      - 8080:80
    depends_on:
      - mysql
